maplibre/maplibre.github.io

index.html
Fix for *Change redirect for MapLibre.org to MapLibre project #1*
=> Update redirect link

_layouts/default.html, src/index.html
Many links and images are only conveyed to visual users.
This PR:
(In the case of for example SVGs, `<title>` _could_ provide the accessible name, but that would display a tooltip on hover (looks similar to that of the `title` attribute) which I didn't want to impose so I went with `aria-label` instead.)
=> [accessibility] Add text alternatives for images & accessible names to links

src/projects.html
Make it more clear to the user that MapTiler can be used as an example how to integrate MapLibre products and repo's.
=> Make it more clear that MapTiler has an example implementation of MapLibre

content/projects/maplibre-gl-js/index.md
Updates the link from maplibre-gl-native to maplibre-gl-js
=> Fix link to maplibre-gl-js

content/_index.html, content/projects/maplibre-gl-js/index.md, content/projects/maplibre-native/index.md
Since finalising the transition from JS to TS, we should update our communication to reflect that.
=> Emphasize that maplibre-gl-js is written in TS

content/about.html
Aligning the about page to our https://github.com/maplibre/maplibre/blob/main/CHARTER.md
=> Align about page to charter

content/sponsors.html
Add a textual link to MIERUNE Inc. since they are sponsoring us at the newly created Stone tier.
https://github.com/maplibre/maplibre/issues/110
=> Add MIERUNE textual link

data/community.json
Adds people who contributed to MapLibre to the map at https://maplibre.org/community/
If you are in this list, it is because your GitHub handle appears in the public commit history of a repo in the MapLibre GitHub organization. Your location was taken from your public GitHub profile.
If you would like to be removed, let me know and I will delete your entry.
People included are: 
@zhangyiatmicrosoft, @VehpuS, @moshe-gr-albo, @zavalit, @pgoldberg, @gzurbach, @cndv3996, @guimochila, @blymemikkel, @caspg, @gregsadetsky, @artakka, @sjg-wdw, @alanchenboy, @carlonzo, @thehoneymad,
=> Add community members

content/news/2023-01-03-aws-maplibre-plugins.md
New "news" blog post on AWS analysis and recommendations for developing plugin support and interoperability for both MapLibre and Mapbox.
=> maplibre plugin interoperability

content/news/2023-01-16-announcement-ovi.md
Adds a news article about Ovi starting as Maintainer Native.
Since we anyway announce all news articles on Twitter and LinkedIn for more visibility, I suggest that when we do a news article, we also already add the tweet text and we get 2 Board members approving it. Like that, when we merge the news article, we can directly put the link on twitter, linkedin.
Twitter text:
> With Ovidiu Voda starting today, we are proud to now have two people working as Maintainers on MapLibre GL Native. Please give Ovi a warm welcome!
=> Announce Ovi starts as Maintainer

assets/main.js
The default position in the top-right corner makes them inaccessible because of the "Donate" banner.
See [OSM US Slack thread](https://osmus.slack.com/archives/C01G3D28DAB/p1674466211569029). Closes #115.
=> Move navigation control to bottom right corner

content/news/2023-01-20-bounty-directions.md
Adds an announcement about the Bounty Directions.
The tweet would be:
> The MapLibre Bounty Program will support the following cross-project directions: Terrain3D, globe view, documentation, performance, Brahmic/Indic scripts, MapLibre Innovation Lab.
Before publishing, we should make sure that the following is done:
=> Announce Bounty Directions

content/roadmap/step-by-step-bounties-guide/_index.md
Adds a note to the bounty guide that people can suggest epics, i.e., multiple tickets that push forward in one of the bounty directions.
=> Add note on epics for bounties

content/sponsors.html
The Meta logo looks just a bit too big visually on maplibre.org/sponsors. This pull request makes it the same size as the AWS logo which should look a bit better...
=> Resize meta logo

content/news/2023-04-14-maplibre-newsletter-april-2023/index.md
Latest newsletter slipped under the radar in #158
=> Update april newsletter, renaming MapLibre Native

content/_index.html, content/community.html, layouts/partials/head.html, layouts/partials/title-header.html
Both these changes are putting the content in focus, as it currently drowns a bit in "MapLibre, MapLibre, MapLibre, .."
**Before** 
**After**
**Before**
**After**
=> Fix page titles (banner and tab title)

content/projects/maplibre-native/index.md
We have our own Android examples now, with more examples coming.
I think it makes sense to keep using the MdBook for this and not set up yet another static site generator.
It turns out is is able to include source code, so we can do literal programming with the example app and we will have a lot of code to draw from: https://rust-lang.github.io/mdBook/format/mdbook.html#including-portions-of-a-file
=> Update Android examples link

content/jobs.html
We have a new job application form link from hubspot. The fields are still the same as before.
=> Update HubSpot job application form link

content/news/2023-05-23-maplibre-gl-js-v3/index.md
Add cover image prepared by Duje (GL JS v3) to twitter cards - it says MapLibre all over in Title and Description, and Post text, so it shouldn't be too confusion that it's us.
Closes https://github.com/maplibre/maplibre/issues/285
=> Add twitter meta tags

layouts/partials/head.html
When in an embed somewhere, the /img/image.png doesn't seem to work well
=> make urls absolute for standard twitter img

content/projects/martin/index.md
Demo: https://martin.maplibre.org
Docs: https://maplibre.org/martin
=> Add Martin Docs link

content/sponsors.html, layouts/partials/nav.html
This is a small part of simplifying sitemap a bit. #189 
This donation link still exist under the sponsors page:
=> Remove github Donate from main menu

content/about/_index.md, content/jobs.html
Part of #189 
The Jobs page had a good intro to the organization, so it's moved to the about page:
This is the jobs page after:
This is the about page after:
=> Move org description from jobs to about page

content/sponsors.html
this makes all silver tier sponsors same width, and adjust gold so it's not completely out of proportions (it seemed very large), and add a min-width so icons doesn't disappear on mobile..
before:
after:
=> Adjust widths of sponsor page

content/projects/maplibre-gl-js/index.md
Update link of API Docs / Plugins to the new page
=> Update link to gl js docs

layouts/shortcodes/github-user.html
Closes #224 
Related to #223 
We currenlty use the github username to call github API to fetch the github username... As suggested, let's not do that
=> Fix github handle links

content/roadmap/metal/_index.md
This PR adds the Metal reports from Steve to the website.
They are hosted on GitHub (see #222).
=> Add Metal reports

layouts/partials/head.html
Following https://gohugo.io/templates/rss/ this add `<link rel="alternate" type="application/rss+xml" href="http://localhost:1313/news/index.xml" title="MapLibre" />` to the `head`.
---
Closes https://github.com/maplibre/maplibre.github.io/issues/221
=> Add rss/atom feed to header

layouts/partials/footer.html, layouts/partials/nav.html
When changing between pages, the navbar jumps, because the logo loads too tall on pageload. This fixes that,
=> Fix jumping nav bar

assets/main.js, content/news/2022-05-20-terrain3d.md
I would like to suggest using the now preferred https://tile.openstreetmap.org URL instead of the current one, see
https://github.com/openstreetmap/operations/issues/737
=> Use preferred tile.openstreetmap.org URL

content/_index.html
* fix Martin label to be consistent with others
* make links point to our book
=> a bit better martin description and label

content/roadmap/_index.md
=> make roadmap readable

content/_index.html
=> Add maputnik

content/news/2024-01-30-maplibre-newsletter-january-2024/index.md
Thanks for the inputs in https://github.com/maplibre/maplibre.github.io/issues/291
=> Add newsletter January

content/_index.html, data/community.json
Should be pretty straightforward. I always get a bit bugged when I see "API Documentation" as if it were _the_ MapLibre native (C++) API 😂
=> Improve Android link; add myself to the community map

content/_index.html
The [iOS documentation](https://maplibre.org/maplibre-native/ios/latest/documentation/maplibre/) hosted by MapLibre now has some examples, it's no longer just API documentation. This PR updates the link text to reflect that.
The MapTiler iOS examples haven't been updated for 6.0.0, so I removed the link because it may be confusing. It's still useful for UIKit, but we should host our own documentation. Thanks MapTiler for bridging the gap with the very scarce documentation for MapLibre Native iOS the past few years.
=> Update iOS Documentation Link

content/jobs/_index.html, content/jobs/developer-job-posting/_index.html
=> Header for bounty hunting on jobs page

content/_index.html
Outdated and examples are now part of MapLibre iOS Documentation.
I intended to include this in https://github.com/maplibre/maplibre.github.io/pull/314
=> Remove iOS Examples LInk

content/_index.html
I think we should link to Maptunik itself from the homepage rather than the GitHub repo.
=> Link to Maputnik

.devcontainer/devcontainer.json
Use image with more up-to-date Hugo version than default image for dev container.
https://docker.hugomods.com/
=> Configure devcontainer.json with hugomods/hugo

src/components/TitleHeader.astro, src/content.config.ts, src/content/roadmap/blending-modes/index.mdx, src/content/roadmap/community-governance/index.mdx, src/content/roadmap/documentation/index.mdx, src/content/roadmap/globe-view/index.mdx, src/content/roadmap/ios-android-release/index.mdx, src/content/roadmap/js-docs/index.mdx, src/content/roadmap/lightweight-renderers/index.mdx, src/content/roadmap/metal/index.mdx, src/content/roadmap/modernize-codebase/index.mdx, src/content/roadmap/non-mercator-projection/index.mdx, src/content/roadmap/performance/index.mdx, src/content/roadmap/project-website/index.mdx, src/content/roadmap/svg-symbol-source/index.mdx, src/content/roadmap/terrain3d-improvements/index.mdx, src/content/roadmap/terrain3d/index.mdx, src/content/roadmap/typescript/index.mdx, src/content/roadmap/vulkan/index.mdx, src/content/roadmap/writing-systems/index.mdx, src/pages/roadmap/[...slug].astro, src/pages/roadmap/index.astro, src/pages/roadmap/step-by-step-bounties-guide/index.mdx
This makes the roadmap items into a proper content collection, instead of hardcoding them on the overview page.
The roadmap items follow the schema:
```ts
const roadmapItems = defineCollection({
loader: glob({ pattern: "**/*.mdx", base: "./src/content/roadmap" }),
schema: ({ image }) =>
z.object({
title: z.string(),
heroImage: image(),
status: z.enum(["under-consideration", "in-progress", "released"]),
bountyLink: z.optional(z.string()),
bountyActive: z.optional(z.boolean()),
}),
});
```
Before:
After
Before:
After
=> Cleanup Roadmap page

src/content.config.ts, src/content/roadmap/blending-modes/index.mdx, src/content/roadmap/community-governance/index.mdx, src/content/roadmap/documentation/index.mdx, src/content/roadmap/globe-view/index.mdx, src/content/roadmap/ios-android-release/index.mdx, src/content/roadmap/js-docs/index.mdx, src/content/roadmap/lightweight-renderers/index.mdx, src/content/roadmap/metal/index.mdx, src/content/roadmap/modernize-codebase/index.mdx, src/content/roadmap/non-mercator-projection/index.mdx, src/content/roadmap/performance/index.mdx, src/content/roadmap/project-website/index.mdx, src/content/roadmap/svg-symbol-source/index.mdx, src/content/roadmap/terrain3d-improvements/index.mdx, src/content/roadmap/terrain3d/index.mdx, src/content/roadmap/typescript/index.mdx, src/content/roadmap/vulkan/index.mdx, src/content/roadmap/writing-systems/index.mdx, src/pages/roadmap/[...slug].astro, src/pages/roadmap/index.astro
I find the roadmap is drowning a bit in bounty info. All the info is repeated inside each roadmap items.
Before:
After
For the released date I've also added that to the content collection, so released features are sorted
Before:
After:
Removing redundant information, the view for single entries are updated:
Before
After
=> Cleanup roadmap - bounty and released date

src/content/news/2025-02-03-maplibre-newsletter-january-2025/index.mdx
Per chat with maintainers, it is best to retain all the meetings on the same day. So we are pushing it all to 19 Feb instead of 12 Feb. This PR updates the details in the newsletter and the timings in the notimezone link.
=> Update monthly meeting times

package-lock.json, package.json
this hasn't crashed until now because npm happen to be very loose about dependencies, but the build script would break with any other package managers unless it's stated explicit because it uses sharp.
try i.e.
- delete node_modules
- pnpm i
- pnpm run dev
=> add sharp explicit as depenency

src/components/CommunityMap.tsx
This PR addresses an issue with the Community Map functionality, which was failing due to an undefined return when attempting to access an invalid property href from the community.json file.
Key Changes:
- Replaced the incorrect property `href` with the correct property `github` to ensure the correct URL to GitHub member accounts.
=> fix(community-map): replace href to github property

astro.config.mjs, src/layouts/Layout.astro
@birkskyum you seem to have commented this one out.
I think that view transitions ([docs on this feature](https://docs.astro.build/en/guides/view-transitions/)) seem to be a better experience.
| before | after |
|--------|--------|
| ![Recording 2025-04-21 at 23 23 48](https://github.com/user-attachments/assets/f0e128ee-02d6-4ec6-94aa-4e081b7d4217)| ![after](https://github.com/user-attachments/assets/e671bf53-3e5d-4c91-b9dc-aca2cb023497) |
I added the prefetching part mostly to make this apparent to other devs.
Using the view transitions automatically enables this.
After experimenting with a few options, I think that the default (fading) works nicely for our site compared to the other build-in animation (slide).
If one of you has strong oppinions on this, I am happy to add them and post …
=> feat: enable view-transitions (and prefetching)

src/content/news/2025-01-05-maplibre-newsletter-december-2024/index.mdx
related: https://github.com/maplibre/maplibre/issues/441
the old docs url no longer works because GH does not redirect Pages urls
=> update maplibre-compose urls

.github/ISSUE_TEMPLATE/newsletter.md
In spite of :
* moving the template to a dedicated folder within `.github` and
* adding a config.yml file,
issue creation does not list the template during issue creation. Looks like it is mandatory to include the frontmatter within the template so that the content is not ignored.
=> Add frontmatter to template

src/content/news/2025-07-02-maplibre-newsletter-june-2025/index.mdx
This PR includes a list of MapLibre's talks and workshops at this year's FOSS4G Europe conference. Using a HTML table for better formatting flexibility.
=> Include a list of FOSS4G talks to newsletter

src/pages/index.astro
TODO: would be great to introduce a proper tile spec section, just like other primary projects
=> add maplibre spec link
