maplibre/maplibre.github.io

- _layouts/default.html
See motivation in https://github.com/maplibre/maplibre-gl-js/pull/156.
> [accessibility] Remove meta viewport's `minimum-scale` and `maximum-scale`

- assets/map-preview.js
The navbar was broken on mobile because of missing JS.
> Fix collapsible navbar

- layouts/_default/section.html
- layouts/_default/single.html
- layouts/author/list.html
- layouts/author/terms.html
- layouts/categories/taxonomy.html
- layouts/news/single.html
- layouts/partials/post-list.html
- layouts/partials/title-header.html
> Refactor and cleanup

- assets/map-preview.js
> Disable rotation on map

- assets/main.js
> Zoom to bounds of community

- content/news/2021-10-13-steering-committee-notes.md
- content/news/2021-11-10-steering-committee-notes.md
- content/news/2022-02-09-steering-committee-notes.md
- content/news/2022-03-09-steering-committee-notes.md
- content/news/2022-04-06-steering-committee-notes.md
- content/news/2022-05-06-maplibre-rs-weekly.md
- content/news/2022-05-13-maplibre-rs-weekly.md
- layouts/shortcodes/github-issue.html
- layouts/shortcodes/github-user.html
Add weekly report for maplibre-rs
> Add weekly report for maplibre-rs

- layouts/_default/section.html
- layouts/author/terms.html
- layouts/categories/taxonomy.html
- layouts/partials/post-list.html
- layouts/projects/section.html
> Fix columns and paddings

- assets/custom.scss
- assets/main.js
- content/_index.html
- content/community.html
- content/news/2022-05-20-terrain3d.md
- package-lock.json
- package.json
This is an attempt to show a terrain 3D map in a news article. Unfortunately the map spans much more area than what I would like.
@maxammann  can you help me bounding the map to a reasonable box somewhere below the text?
> Add terrain example

- content/news/2022-05-23-maplibre-rs-monthly.md
Upsi, forgot to set draft false
> Publish maplibre-rs monthly

- layouts/partials/head.html
> Add hash to JS file to avoid caching issues

- content/news/2022-06-10-mierune-announcement.md
- layouts/_default/section.html
- layouts/author/terms.html
- layouts/partials/post-list.html
- layouts/projects/section.html
Thanks MIERUNE Inc. for sponsoring us. To understand a bit better the motivation and background of this, we would like to share the following interview.
@dayjournal let me know if I should fix something...
> Add MIERUNE announcement

- assets/main.js
https://github.com/maplibre/community is archived
> Updated map link

- config.toml
- content/_index.html
Fixes the headline in the HTML headers to be the same as in the frontpage.
> Fix headline in HTML headers

- .vscode/tasks.json
- content/news/2022-08-24-maplibre-rs-paper.md
Must be published before Friday :)
> Add post about maplibre-rs paper

- content/projects/maplibre-native/index.md
> Add example links

- content/about.html
- content/charter.html
- layouts/shortcodes/charter.html
Feel free to suggest a better place from where to link.
> Add charter for more visibility

- .vscode/settings.json
- content/news/2022-09-24-maplibre-rs-monthly/index.md
- layouts/shortcodes/page-figure.html
> maplibre-rs monthly

- content/about.html
This draft of the Governing Board member bios is taken from the self-nominations at https://github.com/maplibre/maplibre/discussions/78. Please adjust your text according to your needs.
@birkskyum @HarelM @lseelenbinder @klokan @nyurik
> Add Governing Board member bios

- content/jobs.html
It would be great if some people from the community did apply to the open positions, so let's mention that...
> Motivate community members to apply

- content/news/2022-10-07-oliver-coordinator.md
I put you as author, @nyurik, because it would sounds so strange if I was it...
> Announce Oliver is Coordinator

- content/news/2022-10-28-metal-announcement/index.md
@wipfli here are stamen's edits -- let me know what you think!
> Metal announcement stamen edits

- content/news/2023-01-03-announcement-bart.md
> Add news announcement Bart

- content/jobs.html
Open developer applications again since we have now the bounty directions https://github.com/maplibre/maplibre.github.io/pull/113
> Open Developer Role again on jobs page

- content/authors/ianthetechie/_index.md
- content/news/2023-02-08-maplibre-react-native-announcement.md
Announcement to finalize https://github.com/maplibre/maplibre/issues/134.
> MapLibre React Native announcement

- content/roadmap/_index.md
- content/roadmap/documentation/_index.md
- content/roadmap/globe-view/_index.md
- content/roadmap/maplibre-innovation-lab/_index.md
- content/roadmap/performance/_index.md
- content/roadmap/step-by-step-bounties-guide/_index.md
- content/roadmap/terrain3d-improvements/_index.md
- content/roadmap/writing-systems/_index.md
Adds a step-by-step guide on Bounties.
> step by step

- README.md
Modifications to our website should be approved by at least one Governing Board or Team member. Ideally it should be someone from the Team because we should focus on operations things like maintaining the website...
> Add pull requests approval note

- content/news/2023-02-14-maplibre-newsletter-february-2023.md
- content/news/2023-02-16-maplibre-newsletter-february-2023.md
This is a newsletter about things which have been going on at MapLibre in the last month.
Feel free to add your points to the existing sections or create a new section for other projects in the MapLibre github organization.
> Add newsletter Feb

- content/about/_index.md
- content/community.html
> list community info on the community page

- config.toml
- layouts/robots.txt
> Add robots txt

- content/news/2023-05-23-maplibre-gl-js-v3/index.md
It's apparently very counter intuitive to have
header
content
image
this PR makes it
header
image
content
> image above text - more intuitive

- content/projects/martin/index.md
> Add Martin tile server to list of projects

- content/projects/additional-projects.md
- content/projects/maplibre-gl-js/index.md
> Move web plugins to gl js

- content/news/2023-05-18-maplibre-newsletter-may-2023/index.md
- MapLibre User Group Japan event dates changed
> news-may-2023-change

- assets/main.js
- config.toml
- content/community.html
- layouts/shortcodes/community-json.html
> Randomize community members and improve performance

- package-lock.json
- package.json
our main map on the website was running a quite old version.
> bump maplibre 2.3->3.1

- layouts/partials/post-list.html
- Add some space
- Make title bold
> Improve formatting of news list

- content/sponsors.html
Updates the sponsors website and the sponsorship docs.
> Update sponsorship program sep

- content/sponsors.html
Sorry I used the wrong link for the sponsorship slide deck. Should be fixed here.
> Fix sponsorship link

- README.md
Removes the specification of how pull requests are approved. We also don't have this rule in other repos. In the end, anyone with write access can approve and merge pull requests.
> Pull request approval rules

- assets/custom.scss
- content/news/2023-10-30-maplibre-newsletter-october-2023/index.md
> newsletter october

- content/about/_index.html
> Fix reports link

- content/_index.html
> Remove maputnik

- content/roadmap/_index.md
This pull request enables the previous roadmap again. We may want to fix some things going forward, but the most important to me seems to have the page online again.
> Enable roadmap

- content/about/_index.html
Removes the alumni section from the website.
> Remove alumni section

- content/roadmap/metal/_index.md
Report from Steve for November 2023.
> Add November 2023 Metal status report

- content/news/2023-08-02-governing-board-elections-2023/index.md
- content/news/2023-11-30-maplibre-newsletter-november-2023/index.md
- content/news/2023-12-30-maplibre-newsletter-december-2023/index.md
- content/news/2024-01-30-maplibre-newsletter-january-2024/index.md
Fixes missing newsletters on https://maplibre.org/categories/newsletter/
> Fix categories of newsletter posts

- assets/main.js
> Respect prefers-reduced-motion on moving map in home screen

- content/jobs.html
- content/jobs/_index.html
- content/jobs/coordinator-job-posting/_index.html
- content/jobs/developer-job-posting/_index.html
- content/jobs/senior-engineer-web-job-posting/_index.html
Adds job postings for the following roles:
- Coordinator
- Senior Engineer Web
- Developer
> Job postings

- content/jobs/_index.html
- content/jobs/coordinator-job-posting/_index.html
- content/jobs/developer-job-posting/_index.html
- content/jobs/senior-engineer-web-job-posting/_index.html
As discussed in meeting. This only changes file content, so existing links doesn't breaks.
> Rename senior engineer web to graphics engineer - maplibre gl js

- assets/custom.scss
- content/about/_index.html
- content/about/isaac/_index.md
- content/about/meena/_index.md
- content/about/ramya/_index.md
- content/news/2024-10-04-new-team-members/index.md
Announcing updates to team
@wipfli
> News on Team members

- content/news/2024-10-11-farewell-oliver/index.md
> Blog post announcing Oliver's exit

- content/news/2024-10-30-maplibre-newsletter-october-2024/index.md
> Monthly meetings timezone update and conference addition to newsletter

- content/news/2024-10-30-maplibre-newsletter-october-2024/index.md
Updated the google form link for developer connect with the latest one.
> Update google form link

- assets/custom.scss
- layouts/_default/_markup/render-heading.html
Resolves #299
Screenshots after the change:
> made the heading links only show when hovering over them

- package-lock.json
- package.json
- src/components/LandingPageMap.tsx
Zooming around on globe
https://github.com/user-attachments/assets/e78b79af-76db-4f85-98da-fe0e12c49fd3
> show globe on landing

- src/content/news/2024-10-04-new-team-members/index.mdx
- src/content/news/2024-10-11-farewell-oliver/index.mdx
- src/content/news/2024-10-30-maplibre-newsletter-october-2024/index.mdx
- src/content/news/2024-11-12-team-updates/index.mdx
As requested by Meena, removed her name references from the following posts:
* news/2024-11-12-team-updates/
* news/2024-10-11-farewell-oliver/
* news/2024-10-30-maplibre-newsletter-october-2024/
* news/2024-10-04-new-team-members/
> Remove references as requested by Meena

- src/content/news/2024-10-04-new-team-members/index.mdx
- src/content/news/2024-10-11-farewell-oliver/index.mdx
- src/pages/about/index.astro
Isaac stepped down from his role on 31 Dec 2024. This PR removes Isaac from the team page.
We are grateful for or all your contributions Isaac 🙏 - wishing you the very best!
> Team page update

- src/content/news/2025-02-03-maplibre-newsletter-january-2025/index.mdx
PR to update GL JS meeting time in the newsletter
> Meeting time updates

- src/content/news/2025-03-03-maplibre-newsletter-february-2025/index.mdx
> Fix last newsletter

- src/content/news/2025-03-31-maptiler-announcement/index.mdx
PR to fix the logos flexible for mobile view
> Make the logos responsive on mobile devices

- src/content/news/2025-04-04-maplibre-newsletter-march-2025/index.mdx
I also added a new section for MapLibre Style Spec. I think it makes sense this this applies for both Native and Web.
> Clarify state of global state proposal

- .github/newsletter.md
We plan to use a separate ticket for each monthly newsletter, so maintaining a template will be handy.
> Template for newsletter inputs

- src/content/team.json
I somehow fucked up this copy paste task.
Sorry @HarelM 😅
> fix(about): sligtly harel being credited as mainainer of native instead of gl js

- src/components/Sponsors.tsx
- src/pages/sponsors/index.astro
Script that'll on browser refresh shuffle the list of sponsors.
cc @ramyaragupathy , i'm just sharing it here, in case want it this is how it can be implemented.
> shuffle sponsor on refresh

- src/content/bio/frank/index.md
- src/content/board.json
Currently the link on the board site for me 404s.
This fixes this by adapting my application 😉
> chore: add a bio link for frank

- package-lock.json
- package.json
- src/layouts/Layout.astro
this is a bit of a wild guess..
Maybe the issue that @HarelM is experiencing comes from two versions of boostrap existing?
Unlikely to be the case, but maybe?
> chore(deps): bump bootstrap

- src/pages/projects/native.astro
based on the comment on slack, we might want to reword this section.
> feat: update maplibre native marketing talking points

- src/content/news/2025-10-04-maplibre-newsletter-september-2025/index.mdx
Missed Yuri's inputs in the [original PR](https://github.com/maplibre/maplibre.github.io/pull/476), patching it here.
> Patch: Sep 2025 newsletter
